// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nanoprobes/v0/tester/tester.proto

#include "nanoprobes/v0/tester/tester.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace tester {
constexpr AMessage::AMessage(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : first_seen_(nullptr){}
struct AMessageDefaultTypeInternal {
  constexpr AMessageDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AMessageDefaultTypeInternal() {}
  union {
    AMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AMessageDefaultTypeInternal _AMessage_default_instance_;
}  // namespace tester
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_nanoprobes_2fv0_2ftester_2ftester_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_nanoprobes_2fv0_2ftester_2ftester_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_nanoprobes_2fv0_2ftester_2ftester_2eproto = nullptr;

const uint32_t TableStruct_nanoprobes_2fv0_2ftester_2ftester_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tester::AMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tester::AMessage, first_seen_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::tester::AMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tester::_AMessage_default_instance_),
};

const char descriptor_table_protodef_nanoprobes_2fv0_2ftester_2ftester_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n!nanoprobes/v0/tester/tester.proto\022\006tes"
  "ter\032\037google/protobuf/timestamp.proto\":\n\010"
  "AMessage\022.\n\nfirst_seen\030\001 \001(\0132\032.google.pr"
  "otobuf.TimestampB\010Z\006testerb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto = {
  false, false, 154, descriptor_table_protodef_nanoprobes_2fv0_2ftester_2ftester_2eproto, "nanoprobes/v0/tester/tester.proto", 
  &descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto_once, descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_nanoprobes_2fv0_2ftester_2ftester_2eproto::offsets,
  file_level_metadata_nanoprobes_2fv0_2ftester_2ftester_2eproto, file_level_enum_descriptors_nanoprobes_2fv0_2ftester_2ftester_2eproto, file_level_service_descriptors_nanoprobes_2fv0_2ftester_2ftester_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto_getter() {
  return &descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_nanoprobes_2fv0_2ftester_2ftester_2eproto(&descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto);
namespace tester {

// ===================================================================

class AMessage::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& first_seen(const AMessage* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
AMessage::_Internal::first_seen(const AMessage* msg) {
  return *msg->first_seen_;
}
void AMessage::clear_first_seen() {
  if (GetArenaForAllocation() == nullptr && first_seen_ != nullptr) {
    delete first_seen_;
  }
  first_seen_ = nullptr;
}
AMessage::AMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:tester.AMessage)
}
AMessage::AMessage(const AMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_first_seen()) {
    first_seen_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from.first_seen_);
  } else {
    first_seen_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:tester.AMessage)
}

inline void AMessage::SharedCtor() {
first_seen_ = nullptr;
}

AMessage::~AMessage() {
  // @@protoc_insertion_point(destructor:tester.AMessage)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void AMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete first_seen_;
}

void AMessage::ArenaDtor(void* object) {
  AMessage* _this = reinterpret_cast< AMessage* >(object);
  (void)_this;
}
void AMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void AMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:tester.AMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && first_seen_ != nullptr) {
    delete first_seen_;
  }
  first_seen_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.protobuf.Timestamp first_seen = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_first_seen(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tester.AMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp first_seen = 1;
  if (this->_internal_has_first_seen()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::first_seen(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tester.AMessage)
  return target;
}

size_t AMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tester.AMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Timestamp first_seen = 1;
  if (this->_internal_has_first_seen()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *first_seen_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    AMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AMessage::GetClassData() const { return &_class_data_; }

void AMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<AMessage *>(to)->MergeFrom(
      static_cast<const AMessage &>(from));
}


void AMessage::MergeFrom(const AMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tester.AMessage)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_first_seen()) {
    _internal_mutable_first_seen()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(from._internal_first_seen());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AMessage::CopyFrom(const AMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tester.AMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AMessage::IsInitialized() const {
  return true;
}

void AMessage::InternalSwap(AMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(first_seen_, other->first_seen_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AMessage::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto_getter, &descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto_once,
      file_level_metadata_nanoprobes_2fv0_2ftester_2ftester_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace tester
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tester::AMessage* Arena::CreateMaybeMessage< ::tester::AMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tester::AMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
