// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nanoprobes/v0/tester/tester.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_nanoprobes_2fv0_2ftester_2ftester_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_nanoprobes_2fv0_2ftester_2ftester_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_nanoprobes_2fv0_2ftester_2ftester_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_nanoprobes_2fv0_2ftester_2ftester_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_nanoprobes_2fv0_2ftester_2ftester_2eproto;
namespace tester {
class AMessage;
struct AMessageDefaultTypeInternal;
extern AMessageDefaultTypeInternal _AMessage_default_instance_;
}  // namespace tester
PROTOBUF_NAMESPACE_OPEN
template<> ::tester::AMessage* Arena::CreateMaybeMessage<::tester::AMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tester {

// ===================================================================

class AMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tester.AMessage) */ {
 public:
  inline AMessage() : AMessage(nullptr) {}
  ~AMessage() override;
  explicit constexpr AMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AMessage(const AMessage& from);
  AMessage(AMessage&& from) noexcept
    : AMessage() {
    *this = ::std::move(from);
  }

  inline AMessage& operator=(const AMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline AMessage& operator=(AMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const AMessage* internal_default_instance() {
    return reinterpret_cast<const AMessage*>(
               &_AMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AMessage& a, AMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(AMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AMessage& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tester.AMessage";
  }
  protected:
  explicit AMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFirstSeenFieldNumber = 1,
  };
  // .google.protobuf.Timestamp first_seen = 1;
  bool has_first_seen() const;
  private:
  bool _internal_has_first_seen() const;
  public:
  void clear_first_seen();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& first_seen() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_first_seen();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_first_seen();
  void set_allocated_first_seen(::PROTOBUF_NAMESPACE_ID::Timestamp* first_seen);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_first_seen() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_first_seen();
  public:
  void unsafe_arena_set_allocated_first_seen(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* first_seen);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_first_seen();

  // @@protoc_insertion_point(class_scope:tester.AMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* first_seen_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_nanoprobes_2fv0_2ftester_2ftester_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AMessage

// .google.protobuf.Timestamp first_seen = 1;
inline bool AMessage::_internal_has_first_seen() const {
  return this != internal_default_instance() && first_seen_ != nullptr;
}
inline bool AMessage::has_first_seen() const {
  return _internal_has_first_seen();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& AMessage::_internal_first_seen() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = first_seen_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& AMessage::first_seen() const {
  // @@protoc_insertion_point(field_get:tester.AMessage.first_seen)
  return _internal_first_seen();
}
inline void AMessage::unsafe_arena_set_allocated_first_seen(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* first_seen) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(first_seen_);
  }
  first_seen_ = first_seen;
  if (first_seen) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tester.AMessage.first_seen)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* AMessage::release_first_seen() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = first_seen_;
  first_seen_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* AMessage::unsafe_arena_release_first_seen() {
  // @@protoc_insertion_point(field_release:tester.AMessage.first_seen)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = first_seen_;
  first_seen_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* AMessage::_internal_mutable_first_seen() {
  
  if (first_seen_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    first_seen_ = p;
  }
  return first_seen_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* AMessage::mutable_first_seen() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_first_seen();
  // @@protoc_insertion_point(field_mutable:tester.AMessage.first_seen)
  return _msg;
}
inline void AMessage::set_allocated_first_seen(::PROTOBUF_NAMESPACE_ID::Timestamp* first_seen) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(first_seen_);
  }
  if (first_seen) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(first_seen));
    if (message_arena != submessage_arena) {
      first_seen = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, first_seen, submessage_arena);
    }
    
  } else {
    
  }
  first_seen_ = first_seen;
  // @@protoc_insertion_point(field_set_allocated:tester.AMessage.first_seen)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace tester

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_nanoprobes_2fv0_2ftester_2ftester_2eproto
